# Generated by Django 5.2.16 on 2026-07-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadinessQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('is_critical', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Transition Lead', 'Transition Lead'), ('AMS Manager', 'AMS Manager'), ('Contributor', 'Contributor'), ('Security Officer', 'Security Officer')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Partial', 'Partial')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='readiness.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='readiness.readinessquestion')),
            ],
            options={
                'unique_together': {('assessment', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('freshness_date', models.DateField()),
                ('reference', models.CharField(max_length=255)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='readiness.answer')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assessments', to='readiness.userrole'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_assessments', to='readiness.userrole'),
        ),
    ]
