# Generated by Django 4.2.30 on 2026-07-26 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('entity_type', models.CharField(choices=[('Assessment', 'Assessment'), ('Answer', 'Answer'), ('Evidence', 'Evidence')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('field_changed', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='readiness.userrole')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='readiness.assessment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
